#!/bin/bash

#----------------------------------------------------------------------
# Recipe Finder Startup Script
#----------------------------------------------------------------------

export CLASS_PATH=lib/'*'
export CLASS_PATH=$CLASS_PATH:etc

java -Xms128m -Xmx1024m -Djava.util.logging.config.file=etc/logging.properties -cp $CLASS_PATH recipe.RecipeFinder